[package]
name = "Sui"
version = "0.0.1"
published-at = "0x2"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib", override = true }
Prover = { git = "https://github.com/asymptotic-code/sui-prover.git", subdir = "packages/prover", rev = "main", override = true }

[addresses]
sui = "0x2"
